version: "3"

services:
  mysql:
    container_name: ammd_db_mysql
    image: mysql:5.7
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./mysql/mysql:/var/lib/mysql
      - ./mysql/backup.sql:/home/backup/backup.sql
      - ./mysql/backup.sh:/home/backup/backup.sh
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    restart: on-failure

  sftp:
    container_name: ammd_db_sftp
    image: atmoz/sftp
    ports:
      - ${SFTP_PORT}:22
    volumes:
      - ./sftp/ammd_DB_FTP:/ammd_db/ammd_DB_FTP
      - ./sftp/system_config/users.conf:/etc/sftp/users.conf:ro
      - ./sftp/system_config/sshd_config:/etc/ssh/sshd_config:ro

    command: bash -c "
             service ssh start
             && tail -F anything
             && chmod 755 /ammd_db
             "
    restart: on-failure


