version: "3"

services:
  mysql:
    container_name: ammd_db_mysql
    image: hellojaeho/mysql:test2
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./mysql/mysql:/var/lib/mysql
      - ./mysql/system_config:/home/system_config
    environment: 
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    restart: on-failure
    #command: python3 /home/system_config/initialfunc.py

  sftp:
    container_name: ammd_db_sftp
    image: atmoz/sftp
    ports:
      - ${SFTP_PORT}:22
    volumes:
      - ./sftp/ammd_DB_FTP:/ammd_db/ammd_DB_FTP
      - ./sftp/system_config/users.conf:/etc/sftp/users.conf:ro
      - ./sftp/system_config/sshd_config:/etc/ssh/sshd_config:ro

    command: bash -c "
             service ssh start
             && tail -F anything
             && chmod 755 /ammd_db
             "
    restart: on-failure


